# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "magemods_more_song_utils"

# Version of this mod.
version = "1.0.1"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "More Song Utils"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Now you can play Sun's Song and Saria's Song. Plus enable Scarecrow's Song to persist across cycles and enable auto-spawning.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "More ocarina-related improvements."

# Website URL for Thunderstore
website_url = "https://github.com/magemods/mm-more-song-utils"

# Authors of this mod.
authors = [ "magemods" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "magemods_more_song_utils"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [
    "thumb.dds"
]

[[manifest.config_options]]
id = "extra_song_suns"
name = "Enable Sun's Song"
description = ""
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "extra_song_sarias"
name = "Enable Saria's Song"
description = ""
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "scarecrow_auto"
name = "Auto Spawn Scarecrow"
description = "Automatically spawn Pierre as soon as you start playing the ocarina."
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "scarecrow_persist"
name = "Persist Scarecrow's Song"
description = "Persist your Scarecrow's Song across Song of Time resets. You will still have the option to set a new song per cycle."
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"
